export default {
  name: 'dynamics',
  group: 'api',
  description: 'point dynamics + crescendo/decrescendo hairpins',
  song: {
    clef: 'treble',
    timeSignature: [4, 4],
    notes: [
      { dynamic: 'pp' },
      { pitch: 'C5', length: '1/4' },
      { pitch: 'D5', length: '1/4' },
      { hairpin: 'crescendo', start: true },
      { pitch: 'E5', length: '1/4' },
      { pitch: 'F5', length: '1/4' },
      { hairpin: 'crescendo', stop: true },
      { dynamic: 'ff' },
      { pitch: 'G5', length: '1/4' },
      { hairpin: 'decrescendo', start: true },
      { pitch: 'F5', length: '1/4' },
      { pitch: 'E5', length: '1/4' },
      { pitch: 'D5', length: '1/4' },
      { hairpin: 'decrescendo', stop: true },
      { dynamic: 'p' },
      { pitch: 'C5', length: '1/2' },
      { dynamic: 'sfz' },
      { pitch: 'C6', length: '1/2' },
    ],
  },
};
