export default {
  name: 'polymetric',
  group: 'api',
  description: 'Three voices with different time signatures (4/4, 3/4, 6/8). Spans 3 bars of 4/4, 4 bars of 3/4, and 4 bars of 6/8 — same total duration (12 quarters each).',
  song: {
    keySignature: 'C',
    voices: [
      {
        id: 'v1',
        clef: 'treble',
        timeSignature: [4, 4],
        notes: [
          { pitch: 'G4', length: '1/4' },
          { pitch: 'A4', length: '1/4' },
          { pitch: 'B4', length: '1/4' },
          { pitch: 'C5', length: '1/4' },
          { pitch: 'D5', length: '1/4' },
          { pitch: 'C5', length: '1/4' },
          { pitch: 'B4', length: '1/4' },
          { pitch: 'A4', length: '1/4' },
          { pitch: 'G4', length: '1/4' },
          { pitch: 'A4', length: '1/4' },
          { pitch: 'B4', length: '1/4' },
          { pitch: 'C5', length: '1/4' },
        ],
      },
      {
        id: 'v2',
        clef: 'treble',
        timeSignature: [3, 4],
        notes: [
          { pitch: 'E4', length: '1/4' },
          { pitch: 'F4', length: '1/4' },
          { pitch: 'G4', length: '1/4' },
          { pitch: 'A4', length: '1/4' },
          { pitch: 'G4', length: '1/4' },
          { pitch: 'F4', length: '1/4' },
          { pitch: 'E4', length: '1/4' },
          { pitch: 'F4', length: '1/4' },
          { pitch: 'G4', length: '1/4' },
          { pitch: 'A4', length: '1/4' },
          { pitch: 'G4', length: '1/4' },
          { pitch: 'F4', length: '1/4' },
        ],
      },
      {
        id: 'v3',
        clef: 'treble',
        timeSignature: [6, 8],
        notes: [
          { pitch: 'C4', length: '1/8' },
          { pitch: 'D4', length: '1/8' },
          { pitch: 'E4', length: '1/8' },
          { pitch: 'F4', length: '1/8' },
          { pitch: 'G4', length: '1/8' },
          { pitch: 'A4', length: '1/8' },
          { pitch: 'B4', length: '1/8' },
          { pitch: 'A4', length: '1/8' },
          { pitch: 'G4', length: '1/8' },
          { pitch: 'F4', length: '1/8' },
          { pitch: 'E4', length: '1/8' },
          { pitch: 'D4', length: '1/8' },
          { pitch: 'C4', length: '1/8' },
          { pitch: 'D4', length: '1/8' },
          { pitch: 'E4', length: '1/8' },
          { pitch: 'F4', length: '1/8' },
          { pitch: 'G4', length: '1/8' },
          { pitch: 'A4', length: '1/8' },
          { pitch: 'B4', length: '1/8' },
          { pitch: 'A4', length: '1/8' },
          { pitch: 'G4', length: '1/8' },
          { pitch: 'F4', length: '1/8' },
          { pitch: 'E4', length: '1/8' },
          { pitch: 'D4', length: '1/8' },
        ],
      },
    ],
  },
};
